{% set version = "2025.2.9" %}

package:
  name: nox
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nox/nox-{{ version }}.tar.gz
  sha256: d50cd4ca568bd7621c2e6cbbc4845b3b7f7697f25d5fb0190ce8f4600be79768

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - nox = nox.__main__:main
    - tox-to-nox = nox.tox_to_nox:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - argcomplete >=1.9.4,<4.0
    - colorlog >=2.6.1,<7.0.0
    - packaging >=20.9
    - tomli >=1
    - virtualenv >=20.14.1
    - jinja2
    - tox

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - nox
  commands:
    - python -m pip check

about:
  home: https://nox.thea.codes
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible test automation for Python

  description: |
    nox is a command-line tool that automates testing in multiple Python
    environments, similar to Tox. Unlike Tox, Nox uses a standard Python
    file for configuration.
  doc_url: https://nox.thea.codes
  dev_url: https://github.com/wntrblm/nox

extra:
  recipe-maintainers:
    - kynan
    - MarckK
    - tswast
    - henryiii
