{% set version = "2022.8.7" %}

package:
  name: nox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nox/nox-{{ version }}.tar.gz
  sha256: 1b894940551dc5c389f9271d197ca5d655d40bdc6ccf93ed6880e4042760a34b

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv
  entry_points:
    - nox = nox.__main__:main
    - tox-to-nox = nox.tox_to_nox:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - argcomplete >=1.9.4,<2.0
    - colorlog >=2.6.1,<7.0.0
    - packaging >=20.9
    - py >=1.4.0,<2.0.0
    - typing_extensions >=3.7.4  # [py<=38]
    - virtualenv >=14.0.0
    - importlib_metadata  # [py<=38]
    - jinja2

test:
  requires:
    - python
    - pip
  imports:
    - nox
  commands:
    - python -m pip check

about:
  home: https://nox.thea.codes
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Flexible test automation for Python

  description: |
    nox is a command-line tool that automates testing in multiple Python
    environments, similar to Tox. Unlike Tox, Nox uses a standard Python
    file for configuration.
  doc_url: https://nox.thea.codes
  dev_url: https://github.com/wntrblm/nox

extra:
  recipe-maintainers:
    - kynan
    - MarckK
    - tswast
